### ISSUE TITLE
Kanban board for assignment of tasks - Rails Recipes Project

### ISSUE THREAD

**Issue by chelobotix** [chelobotix/Recipe-app#13]
This issue is related to the Kanban board for the Ruby on Rails project [project](https://github.com/chelobotix/Recipe-app/)

There are two members in our group: @limavfabio and @chelobotix .

Link to the Kanban board: https://github.com/users/chelobotix/projects/9/views/1

**Comment by DeliceLydia** [comment]
## Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
# Congratulations! 🎉 

## Highlights
- All cards are created and assigned equally to the members of the team
- Added necessary columns


### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
